name: spotify
description: "Spotify clone, made with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg:
  flutter_bloc:
  hydrated_bloc:
  path_provider:
  firebase_core:
  firebase_auth:
  get_it:
  dartz:
  cloud_firestore:
  just_audio:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/spotify_app_logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/spotify_app_logo.png"
  adaptive_icon_foreground_inset: 25
  web:
    generate: true
    image_path: "assets/images/spotify_app_logo.png"
    background_color: "#000000"
    theme_color: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300

